# Generated by Django 5.2 for Amaris reliability controls.

import uuid

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [("content", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_verified_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set only after server-side gateway verification succeeds.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="verification_source",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Opaque verification method identifier; never store credentials here.",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="PaymentReconciliationRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")],
                        db_index=True,
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("payments_scanned", models.PositiveIntegerField(default=0)),
                ("enrollments_repaired", models.PositiveIntegerField(default=0)),
                ("unresolved_count", models.PositiveIntegerField(default=0)),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Non-sensitive exception class or operational code only.",
                        max_length=120,
                    ),
                ),
            ],
            options={"ordering": ["-started_at"]},
        ),
    ]
