# Generated by Django 5.2.17 on 2026-09-10 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_payment_reliability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(condition=models.Q(('is_published', True)), fields=['-priority', '-created_at', 'expires_at'], name='announcement_live_idx'),
        ),
        migrations.AddIndex(
            model_name='contactenquiry',
            index=models.Index(fields=['status', '-created_at'], name='enquiry_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(condition=models.Q(('is_published', True), ('status', 'published')), fields=['order', 'title'], name='course_live_order_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(condition=models.Q(('featured', True), ('is_published', True), ('status', 'published')), fields=['order'], name='course_featured_live_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(condition=models.Q(('is_published', True)), fields=['course', 'order'], name='module_live_order_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status', '-enrolled_at'], name='enrol_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(condition=models.Q(('is_published', True)), fields=['module', 'order', 'publish_at'], name='lesson_live_order_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationitem',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['location', 'order'], name='nav_active_loc_order_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesection',
            index=models.Index(condition=models.Q(('is_published', True)), fields=['page', 'order'], name='page_section_live_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('enrollment__isnull', True), ('gateway_verified_at__isnull', False), ('status', 'paid')), fields=['created_at'], name='payment_reconcile_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'status', '-created_at'], name='payment_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreconciliationrun',
            index=models.Index(fields=['status', '-started_at'], name='reconcile_status_time_idx'),
        ),
    ]
