# Generated by Django 5.2.17 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_announcement_announcement_live_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactenquiry",
            name="message",
            field=models.TextField(max_length=5000),
        ),
    ]
