# Generated by Django 5.2.17 on 2026-10-07 12:24

import content.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_live_class_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('idempotency_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('programme', models.CharField(choices=[('caps', 'CAPS'), ('ieb', 'IEB'), ('tvet', 'TVET'), ('university', 'University')], max_length=20)),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('mathematical_literacy', 'Mathematical Literacy')], max_length=32)),
                ('level', models.CharField(max_length=80)),
                ('topic', models.CharField(max_length=180)),
                ('details', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default='150.00', max_digits=10)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=20)),
                ('hold_expires_at', models.DateTimeField(db_index=True, default=content.models.video_request_hold_expiry)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_verified_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_sent_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_requests', to='content.studentrecord')),
                ('video', models.ForeignKey(blank=True, help_text='Attach the produced video, then mark the request fulfilled to notify the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_requests', to='content.videoasset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status', '-created_at'], name='videoreq_student_status_idx'), models.Index(fields=['status', 'hold_expires_at'], name='videoreq_hold_status_idx')],
            },
        ),
    ]
