# Generated by Django 5.2.17 on 2026-09-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_live_class_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclassbooking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('payment_review', 'Paid booking requiring review')], db_index=True, default='pending_payment', max_length=20),
        ),
    ]
