# Generated by Django 5.2.17 on 2026-10-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_videorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoasset',
            name='vimeo_hash',
            field=models.CharField(blank=True, help_text="Unlisted/private Vimeo access token (the 'h' value), required to embed private videos.", max_length=64),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='vimeo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='vimeo_video_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='provider',
            field=models.CharField(choices=[('youtube', 'Private YouTube'), ('vimeo', 'Private Vimeo'), ('s3', 'Private S3 upload')], default='youtube', max_length=12),
        ),
    ]
