# Generated by Django 5.2.17 on 2026-10-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_videoasset_vimeo_hash_videoasset_vimeo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='website_url',
            field=models.URLField(default='https://amaris-mathematics-academy-live-students.onrender.com'),
        ),
    ]
