export const academyBrand = {
  name: "Amaris Mathematics Academy",
  shortName: "Amaris",
  managingDirector: "Bethuel Moukangwe",
  phoneDisplay: "071 415 6665",
  phoneHref: "tel:+27714156665",
  email: "bethuelmoukangwe8@gmail.com",
  emailHref: "mailto:bethuelmoukangwe8@gmail.com",
  address: "27 Tshivhase Street, Atteridgeville, Pretoria, Gauteng, 0008",
  addressShort: "27 Tshivhase Street, Atteridgeville, Pretoria",
  addressHref: "https://maps.google.com/?q=27+Tshivhase+Street,+Atteridgeville,+Pretoria,+Gauteng,+0008",
  hours: "Mon–Sun, 07:00–20:00",
  website: "amaris-mathematics-academy.bethuelthipe.chatgpt.site",
  websiteHref: "https://amaris-mathematics-academy.bethuelthipe.chatgpt.site",
  logoPath: "/brand/amaris-academy-mark.png",
} as const;
