apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: amaris-public-tls
spec:
  secretName: amaris-public-tls
  duration: 2160h
  renewBefore: 336h
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  dnsNames:
    - amaris-mathematics-academy.bethuelthipe.chatgpt.site
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amaris-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - amaris-mathematics-academy.bethuelthipe.chatgpt.site
      secretName: amaris-public-tls
  rules:
    - host: amaris-mathematics-academy.bethuelthipe.chatgpt.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amaris-web
                port:
                  number: 80
