import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, ShieldCheck } from "lucide-react";
import { Header } from "@/components/site/header";
import { Footer } from "@/components/site/footer";
import { courses, formatRand } from "@/lib/courses";

export const metadata: Metadata = { title: "Pricing" };

export default function PricingPage() { return <main className="min-h-screen bg-[#f5f7fb]"><Header /><section className="border-b border-[#dce4ef] bg-white"><div className="mx-auto max-w-7xl px-5 py-20 text-center lg:px-8"><p className="eyebrow">Clear pricing</p><h1 className="section-title mx-auto mt-4 max-w-4xl">Choose one course. See the full price upfront.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-[#60708a]">No hidden platform charge. Course access is activated only after PayFast verifies payment.</p></div></section><section className="mx-auto max-w-6xl px-5 py-16 lg:px-8"><div className="grid gap-4">{courses.map((course) => <article key={course.slug} className="flex flex-col justify-between gap-5 rounded-2xl border border-[#dce4ef] bg-white p-6 sm:flex-row sm:items-center"><div><div className="flex gap-2"><span className="rounded-full bg-[#edf3ff] px-3 py-1 text-xs font-bold text-[#1f5bbd]">{course.curriculum}</span><span className="rounded-full bg-[#f0f3f7] px-3 py-1 text-xs font-semibold text-[#60708a]">{course.level}</span></div><h2 className="mt-4 text-xl font-semibold">{course.title}</h2><p className="mt-2 text-sm text-[#60708a]">{course.lessons} lessons · {course.hours} guided hours</p></div><div className="flex items-center justify-between gap-6 sm:justify-end"><p className="text-2xl font-bold">{formatRand(course.price)}</p><Link href={`/courses/${course.slug}`} className="grid size-11 place-items-center rounded-full bg-[#0b2a5b] text-white" aria-label={`View ${course.title}`}><ArrowRight className="size-4" /></Link></div></article>)}</div><div className="mt-10 grid gap-5 rounded-3xl bg-[#0b2a5b] p-7 text-white md:grid-cols-[1fr_1.2fr] md:p-10"><div><ShieldCheck className="size-8 text-[#ffcc66]" /><h2 className="mt-5 text-3xl font-semibold">Included with every course</h2></div><div className="grid gap-3 sm:grid-cols-2">{['Private student dashboard','Structured video lessons','Worked examples','Practice activities','Progress tracking','Secure PayFast checkout'].map((item) => <span key={item} className="flex items-center gap-2 text-sm text-white/75"><Check className="size-4 text-[#6ee7c6]" />{item}</span>)}</div></div></section><Footer /></main>; }
